/**
 * Rentify — Property Seed Script
 * Seeds 10 landlords and 113 realistic rental properties.
 *
 * Usage:
 *   node seed/seedProperties.js            → insert seed data
 *   SEED_CLEAR=true node seed/seedProperties.js → wipe seed data then re-insert
 *
 * Seeded records are identified by email suffix @seedrpk.test on landlords.
 * Cleanup removes properties owned by those landlords + the landlords themselves.
 */

import "dotenv/config";
import mongoose from "mongoose";
import connectDB from "../config/database.js";
import Landlord from "../models/Landlord.js";
import Property from "../models/Property.js";

const SEED_TAG = "@seedrpk.pk";
const CLEAR = process.env.SEED_CLEAR === "true";

// ─── Image Pool (30 picsum URLs — no API key, guaranteed stable) ──────────────
const IMG_POOL = [
  "https://pixabay.com/images/download/jeanvdmeulen-dining-room-3108037_1280.jpg",
  "https://pixabay.com/images/download/clickerhappy-living-room-2732939_1920.jpg",
  "https://images.pexels.com/photos/17924970/pexels-photo-17924970.jpeg",
  "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg",
  "https://images.pexels.com/photos/37253217/pexels-photo-37253217.jpeg",
  "https://images.pexels.com/photos/33320790/pexels-photo-33320790.jpeg",
  "https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6OTA2OTM2NzAxODIxMjgwMjA3/original/5892c016-09e1-454a-b390-329d3590bdd6.jpeg?im_w=720",
  "https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6Mjg3NDUzNDA%3D/original/89f39025-438a-437a-a839-556c1a6c90af.jpeg",
  "https://img.freepik.com/free-photo/3d-rendering-luxury-modern-living-room-with-leather-sofa-lamp_105762-2255.jpg?semt=ais_hybrid&w=740&q=80",
  "https://cdn-blog.zameen.com/blog/wp-content/uploads/2020/06/Types-of-Apartments-in-Pakistan-B-24-06-1024x640.jpg",
  "https://q-xx.bstatic.com/xdata/images/hotel/max600/838434953.jpg?k=1afe5bcc535b6737d3b6b601e7a83a76f8c87348a344c16b488739d06b344f3b&o=&a=1311119",
  "https://media.vrbo.com/lodging/91000000/90920000/90915400/90915326/w905h683x60y0-7ae74f1a.jpg?impolicy=resizecrop&rw=575&rh=575&ra=fill",
  "https://images.olx.com.pk/thumbnails/610939779-400x300.jpeg",
  "https://lid.zoocdn.com/645/430/76e9c631dde3b77934f179be65299b43ee8f0f86.jpg",
  "https://images.olx.com.pk/thumbnails/615555109-400x300.jpeg",
  "https://a0.muscache.com/im/pictures/4ac2fa8a-7fe5-47e5-beb3-3df2823f2734.jpg",
  "https://img.magnific.com/free-photo/dining-area-comfortable-studio-flat-hotel-room_1262-12324.jpg?semt=ais_hybrid&w=740&q=80",
  "https://img.magnific.com/free-photo/cozy-living-room-interior-with-panoramic-window_1262-12322.jpg?semt=ais_hybrid&w=740&q=80",
  "https://a0.muscache.com/im/pictures/hosting/Hosting-1517424985259150923/original/d4b99e17-f56e-4f09-ba39-e9e650350053.jpeg?im_w=720",
  "https://images.unsplash.com/photo-1493809842364-78817add7ffb?fm=jpg&q=60&w=3000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGFwYXJ0bWVudHxlbnwwfHwwfHx8MA%3D%3D",
  "https://static.vecteezy.com/system/resources/thumbnails/069/792/007/small/modern-city-apartment-bedroom-workspace-large-window-urban-view-student-housing-photo.jpg",
  "https://images.olx.com.pk/thumbnails/613797365-400x300.jpeg",
  "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?fm=jpg&q=60&w=3000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8YXBhcnRtZW50fGVufDB8fDB8fHww",
  "https://lid.zoocdn.com/645/430/76e9c631dde3b77934f179be65299b43ee8f0f86.jpg",
  "https://images.olx.com.pk/thumbnails/615555109-400x300.jpeg",
  "https://a0.muscache.com/im/pictures/4ac2fa8a-7fe5-47e5-beb3-3df2823f2734.jpg",
  "https://img.magnific.com/free-photo/dining-area-comfortable-studio-flat-hotel-room_1262-12324.jpg?semt=ais_hybrid&w=740&q=80",
  "https://img.magnific.com/free-photo/cozy-living-room-interior-with-panoramic-window_1262-12322.jpg?semt=ais_hybrid&w=740&q=80",
  "https://a0.muscache.com/im/pictures/hosting/Hosting-1517424985259150923/original/d4b99e17-f56e-4f09-ba39-e9e650350053.jpeg?im_w=720",
  "https://images.unsplash.com/photo-1493809842364-78817add7ffb?fm=jpg&q=60&w=3000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGFwYXJ0bWVudHxlbnwwfHwwfHx8MA%3D%3D",
  "https://static.vecteezy.com/system/resources/thumbnails/069/792/007/small/modern-city-apartment-bedroom-workspace-large-window-urban-view-student-housing-photo.jpg",
  "https://images.olx.com.pk/thumbnails/610939779-400x300.jpeg",
];

// Build image array: 3-4 images cycling through the pool from an offset
function imgs(offset, count = 3) {
  return Array.from({ length: count }, (_, i) => {
    const url = IMG_POOL[(offset + i) % IMG_POOL.length];
    return { public_id: `rentify/seed/${offset}_${i}`, secure_url: url };
  });
}

// Deterministic status distribution: 80% APPROVED, 15% PENDING, 5% REJECTED
function getStatus(pos) {
  const r = (pos * 97 + 31) % 100;
  if (r < 80) return "APPROVED";
  if (r < 95) return "PENDING";
  return "REJECTED";
}

// ─── 10 Landlords ─────────────────────────────────────────────────────────────
const LANDLORD_DATA = [
  {
    name: "Ahmed Raza",
    email: `ahmed.raza${SEED_TAG}`,
    phone: "03001234567",
    cnic: "35202-1234567-1",
    businessAddress: "Office 5, Johar Town Commercial, Lahore",
  },
  {
    name: "Fatima Malik",
    email: `fatima.malik${SEED_TAG}`,
    phone: "03012345678",
    cnic: "35202-2345678-2",
    businessAddress: "B-12, Model Town Extension, Lahore",
  },
  {
    name: "Muhammad Tariq",
    email: `m.tariq${SEED_TAG}`,
    phone: "03023456789",
    cnic: "61101-3456789-3",
    businessAddress: "Plot 44, G-11 Markaz, Islamabad",
  },
  {
    name: "Ayesha Khan",
    email: `ayesha.khan${SEED_TAG}`,
    phone: "03034567890",
    cnic: "61101-4567890-4",
    businessAddress: "F-10/3, Street 4, Islamabad",
  },
  {
    name: "Usman Butt",
    email: `usman.butt${SEED_TAG}`,
    phone: "03045678901",
    cnic: "42101-5678901-5",
    businessAddress: "Plot 7-C, PECHS Block 2, Karachi",
  },
  {
    name: "Sara Qureshi",
    email: `sara.q${SEED_TAG}`,
    phone: "03056789012",
    cnic: "42101-6789012-6",
    businessAddress: "House 23, DHA Phase 6, Karachi",
  },
  {
    name: "Bilal Hussain",
    email: `bilal.h${SEED_TAG}`,
    phone: "03067890123",
    cnic: "36302-7890123-7",
    businessAddress: "Shop 8, Gulgasht Colony Market, Multan",
  },
  {
    name: "Nadia Siddiqui",
    email: `nadia.s${SEED_TAG}`,
    phone: "03078901234",
    cnic: "33100-8901234-8",
    businessAddress: "House 4-B, Peoples Colony, Faisalabad",
  },
  {
    name: "Zafar Iqbal",
    email: `zafar.i${SEED_TAG}`,
    phone: "03089012345",
    cnic: "17301-9012345-9",
    businessAddress: "H No 12, Hayatabad Ph 3, Peshawar",
  },
  {
    name: "Hina Nawaz",
    email: `hina.n${SEED_TAG}`,
    phone: "03090123456",
    cnic: "37405-0123456-0",
    businessAddress: "Office 2, Satellite Town Chowk, Rawalpindi",
  },
];

// ─── Property Specs ───────────────────────────────────────────────────────────
// Each spec: [imgOffset, ownerIdx(0-9), title, description, city, area, address, lat, lng, price, type, totalRooms, availRooms, gender, facilities[]]

const SPECS = [
  // ══════════════════════════════════════════════════════════════════ LAHORE ══
  // ─── Johar Town ───────────────────────────────────────────────────────────
  [
    0,
    0,
    "Modern 2-Bed Apartment in Johar Town",
    "Beautifully designed 2-bedroom apartment on the 4th floor with elevator access and a large balcony. Fully tiled with split ACs in all rooms and 24/7 CCTV security. Walking distance from Johar Town Chowk and major hospitals.",
    "Lahore",
    "Johar Town",
    "Block B, Johar Town, Lahore",
    31.4698,
    74.2728,
    58000,
    "Apartment",
    2,
    1,
    "Any",
    ["WiFi", "AC", "Parking", "Electricity Backup", "Security", "Balcony"],
  ],

  [
    3,
    1,
    "Furnished Studio Flat near Johar Town Mall",
    "Compact, fully furnished studio apartment ideal for working professionals. Comes with an attached bath, split AC, and a well-equipped kitchenette. Utilities included in the rent.",
    "Lahore",
    "Johar Town",
    "Al-Fatah Heights, Block C, Johar Town, Lahore",
    31.4702,
    74.2741,
    39000,
    "Apartment",
    1,
    1,
    "Any",
    ["WiFi", "AC", "Furnished", "Electricity Backup", "Kitchen"],
  ],

  [
    6,
    0,
    "Single Furnished Room near UCP Johar Town",
    "Clean and well-maintained furnished room with an attached washroom available for male students or professionals. High-speed Wi-Fi, electricity backup via solar, and a shared kitchen provided.",
    "Lahore",
    "Johar Town",
    "Iqbal Residency, near UCP Gate 2, Johar Town, Lahore",
    31.4712,
    74.2715,
    18000,
    "Room",
    1,
    1,
    "Male",
    ["WiFi", "Electricity Backup", "Furnished", "Kitchen"],
  ],

  [
    9,
    1,
    "Boys Hostel Accommodation in Johar Town",
    "Well-managed boys hostel with clean furnished rooms available on a monthly basis. Common kitchen, laundry facility, and a study lounge provided. 24-hour security with CCTV at all entry points.",
    "Lahore",
    "Johar Town",
    "House 45, Block D, Johar Town, Lahore",
    31.469,
    74.275,
    13000,
    "Shared",
    6,
    3,
    "Male",
    ["WiFi", "Laundry", "Kitchen", "Security", "Electricity Backup"],
  ],

  // ─── Model Town ───────────────────────────────────────────────────────────
  [
    12,
    0,
    "Spacious Family House in Model Town",
    "Well-maintained 5-marla house with 3 bedrooms, 2 bathrooms, a TV lounge, and a separate kitchen. Covered parking for one car included. Quiet, family-oriented street close to Model Town Park.",
    "Lahore",
    "Model Town",
    "House 12, Block L, Model Town, Lahore",
    31.4816,
    74.3236,
    95000,
    "House",
    3,
    2,
    "Any",
    ["Parking", "Electricity Backup", "Security", "Balcony"],
  ],

  [
    15,
    1,
    "3-Bed Luxury Apartment in Model Town",
    "Premium apartment in a high-rise building with a panoramic view of the city. Features include a modular kitchen, marble flooring, dedicated parking, and 24/7 guard service. Close to educational and medical facilities.",
    "Lahore",
    "Model Town",
    "Model Heights, Block E, Model Town, Lahore",
    31.4821,
    74.3248,
    85000,
    "Apartment",
    3,
    1,
    "Any",
    ["WiFi", "AC", "Parking", "Security", "Electricity Backup", "Balcony"],
  ],

  [
    18,
    0,
    "Lower Portion 2-Bed in Model Town",
    "Neat and clean lower portion of a double-story house with 2 bedrooms and a spacious TV lounge. Separate main entrance, private lawn access, and carport available. All utilities connections are separate.",
    "Lahore",
    "Model Town",
    "Street 15, Block J, Model Town, Lahore",
    31.4809,
    74.3225,
    48000,
    "Private",
    2,
    2,
    "Any",
    ["Parking", "Electricity Backup", "Balcony"],
  ],

  [
    21,
    1,
    "Girls Hostel Room in Model Town",
    "Bright, airy rooms available in a secured girls hostel. On-site warden, 24/7 hot water, laundry facility, and home-cooked meals available on request. Just 5 minutes from Model Town Metro station.",
    "Lahore",
    "Model Town",
    "House 78, Block B, Model Town, Lahore",
    31.4825,
    74.3258,
    16000,
    "Room",
    1,
    1,
    "Female",
    ["WiFi", "Laundry", "Kitchen", "Security", "Furnished"],
  ],

  // ─── Township ─────────────────────────────────────────────────────────────
  [
    24,
    0,
    "Affordable Furnished Room in Township",
    "Neat furnished room suitable for a single person. Attached bathroom, 24/7 electricity backup through generator, and fast Wi-Fi included. Close to Shaukat Khanum Road and major bus stops.",
    "Lahore",
    "Township",
    "Sector B2, Township, Lahore",
    31.4641,
    74.301,
    14000,
    "Room",
    1,
    1,
    "Male",
    ["WiFi", "Electricity Backup", "Furnished"],
  ],

  [
    27,
    1,
    "Shared Rooms for Boys in Township",
    "Budget-friendly shared accommodation for students and working professionals. Rooms can be single or double occupancy. Common kitchen, filtered water, and monthly housekeeping included.",
    "Lahore",
    "Township",
    "House 33, Block C, Township, Lahore",
    31.4635,
    74.302,
    9500,
    "Shared",
    8,
    4,
    "Male",
    ["WiFi", "Kitchen", "Laundry", "Electricity Backup"],
  ],

  [
    0,
    0,
    "1-Bed Apartment in Township",
    "Affordable 1-bedroom apartment on the 2nd floor. Ideal for a couple or a single professional. Tiled flooring, split AC, and a compact kitchen fitted with a gas range.",
    "Lahore",
    "Township",
    "Raza Plaza, Sector A4, Township, Lahore",
    31.4648,
    74.3005,
    36000,
    "Apartment",
    1,
    1,
    "Any",
    ["AC", "Kitchen", "Electricity Backup", "Parking"],
  ],

  // ─── DHA Phase 5 ──────────────────────────────────────────────────────────
  [
    3,
    1,
    "Premium 3-Bed Apartment in DHA Phase 5",
    "Luxuriously furnished 3-bedroom apartment in a prestigious high-rise with a rooftop gym, swimming pool, and concierge service. Each bedroom has a walk-in wardrobe and attached bath. Community area with a café on the ground floor.",
    "Lahore",
    "DHA Phase 5",
    "Emaar Tower, DHA Phase 5, Lahore",
    31.4636,
    74.3981,
    115000,
    "Apartment",
    3,
    1,
    "Any",
    [
      "WiFi",
      "AC",
      "Parking",
      "Security",
      "Furnished",
      "Balcony",
      "Electricity Backup",
    ],
  ],

  [
    6,
    0,
    "1-Kanal House for Rent in DHA Phase 5",
    "Grand 1-kanal house with a lush front lawn, a drawing/dining area, 5 bedrooms with attached baths, a servant quarter, and a 2-car garage. Quiet street with 24/7 security within the community.",
    "Lahore",
    "DHA Phase 5",
    "Street 3, Block D, DHA Phase 5, Lahore",
    31.4629,
    74.3975,
    175000,
    "House",
    5,
    2,
    "Any",
    ["Parking", "Security", "Electricity Backup", "Balcony"],
  ],

  [
    9,
    1,
    "Upper Portion in DHA Phase 5",
    "Tastefully designed upper portion of a 10-marla house. 3 bedrooms with attached baths, a modern kitchen, and a large roof terrace. Separate entrance with intercom. Monthly utilities are billed separately.",
    "Lahore",
    "DHA Phase 5",
    "Lane 7, Phase 5 DHA, Lahore",
    31.4641,
    74.399,
    62000,
    "Private",
    3,
    1,
    "Any",
    ["Parking", "Electricity Backup", "Security", "Balcony"],
  ],

  [
    12,
    0,
    "Furnished Bedroom in DHA Phase 5 Shared Villa",
    "Stylish furnished room in a shared villa with professionals. The villa features a large common lounge, a fully equipped kitchen, fast fibre internet, and covered parking. Weekly cleaning service included.",
    "Lahore",
    "DHA Phase 5",
    "Villa 9, CCA, DHA Phase 5, Lahore",
    31.4622,
    74.3969,
    26000,
    "Room",
    1,
    1,
    "Any",
    ["WiFi", "AC", "Furnished", "Parking", "Security", "Kitchen"],
  ],

  // ─── Gulberg III ──────────────────────────────────────────────────────────
  [
    15,
    1,
    "Modern Office-Converted Apartment in Gulberg",
    "Sleek studio apartment in the heart of Gulberg, converted from a commercial space. Features polished concrete floors, exposed brick walls, a kitchenette, and huge windows. Metro-bus stop just 200 metres away.",
    "Lahore",
    "Gulberg III",
    "Liberty Market Area, Gulberg III, Lahore",
    31.5236,
    74.3413,
    55000,
    "Apartment",
    1,
    1,
    "Any",
    ["WiFi", "AC", "Furnished", "Electricity Backup", "Security"],
  ],

  [
    18,
    0,
    "2-Bed Flat in Gulberg with City View",
    "Contemporary 2-bedroom flat on the 7th floor of a premium building with a panoramic view of MM Alam Road. Open-plan kitchen and living area, hardwood flooring throughout, and covered underground parking.",
    "Lahore",
    "Gulberg III",
    "MM Alam Road, Gulberg III, Lahore",
    31.5242,
    74.3402,
    78000,
    "Apartment",
    2,
    1,
    "Any",
    ["WiFi", "AC", "Parking", "Security", "Balcony", "Electricity Backup"],
  ],

  [
    21,
    1,
    "Private Room for Professional in Gulberg",
    "Spacious private room with an attached bath in a managed residence. High-speed internet, a shared TV lounge, housekeeping twice a week, and a backup generator are included. Ideal for corporate executives visiting Lahore.",
    "Lahore",
    "Gulberg III",
    "Main Boulevard Gulberg III, Lahore",
    31.523,
    74.342,
    22000,
    "Room",
    1,
    1,
    "Any",
    ["WiFi", "AC", "Furnished", "Security", "Electricity Backup"],
  ],

  [
    24,
    0,
    "Upper Portion in Gulberg III",
    "Bright and airy upper portion of a residential house. 2 bedrooms, a lounge, and a fully tiled kitchen. Rooftop access available. Located on a quiet residential street, just minutes from Kalma Chowk.",
    "Lahore",
    "Gulberg III",
    "Street 5, Block C, Gulberg III, Lahore",
    31.5228,
    74.3435,
    52000,
    "Private",
    2,
    2,
    "Any",
    ["Electricity Backup", "Balcony", "Parking"],
  ],

  // ─── Faisal Town ──────────────────────────────────────────────────────────
  [
    27,
    1,
    "1-Bed Apartment in Faisal Town",
    "Affordable 1-bedroom apartment in a well-managed building. Features a fitted kitchen, tiled bathroom, and split AC. Close to Faisal Town market, ATM, and a bakery. Ideal for a couple or single occupant.",
    "Lahore",
    "Faisal Town",
    "Block A, Faisal Town, Lahore",
    31.4855,
    74.3069,
    34000,
    "Apartment",
    1,
    1,
    "Any",
    ["AC", "Kitchen", "Electricity Backup"],
  ],

  [
    0,
    0,
    "Cosy Room near Faisal Town Market",
    "Well-maintained furnished room in a peaceful neighbourhood. Attached bathroom, daily housekeeping, electricity backup, and meals available on request. Walking distance to daily amenities.",
    "Lahore",
    "Faisal Town",
    "Near Faisal Town Chowk, Lahore",
    31.4862,
    74.3078,
    15000,
    "Room",
    1,
    1,
    "Male",
    ["WiFi", "Electricity Backup", "Furnished", "Kitchen"],
  ],

  [
    3,
    1,
    "Family House in Faisal Town",
    "Well-constructed 5-marla house with 3 bedrooms, a study room, drawing-dining, and a kitchen. Renovated bathroom fittings, generator backup, and a small garden at the back. Near Johar Town Road and UCP.",
    "Lahore",
    "Faisal Town",
    "Block C, Faisal Town, Lahore",
    31.4847,
    74.306,
    85000,
    "House",
    3,
    2,
    "Any",
    ["Parking", "Electricity Backup", "Security"],
  ],

  // ══════════════════════════════════════════════════════════════ ISLAMABAD ══
  // ─── G-11 ─────────────────────────────────────────────────────────────────
  [
    6,
    2,
    "2-Bed Flat in G-11 Markaz Near Metro",
    "Comfortable 2-bedroom flat just 3 minutes from G-11 Metro Station. Includes modular kitchen, split ACs, 24/7 WASA water supply, and dedicated parking. Sector is well-lit and patrolled.",
    "Islamabad",
    "G-11",
    "G-11/2, Near Markaz, Islamabad",
    33.6939,
    73.002,
    55000,
    "Apartment",
    2,
    1,
    "Any",
    ["WiFi", "AC", "Parking", "Electricity Backup", "Security"],
  ],

  [
    9,
    3,
    "Furnished Studio in G-11 Islamabad",
    "Smart, fully furnished studio on the 3rd floor of a modern block. Equipped with a mini fridge, microwave, split AC, and a pull-down double bed. Ideal for diplomats, students, or short-term stays.",
    "Islamabad",
    "G-11",
    "Street 8, G-11/3, Islamabad",
    33.6944,
    73.001,
    42000,
    "Apartment",
    1,
    1,
    "Any",
    ["WiFi", "AC", "Furnished", "Electricity Backup"],
  ],

  [
    12,
    2,
    "Room for Rent in G-11 Islamabad",
    "Neat furnished room in a shared house occupied by working professionals. Attached bathroom, unlimited Wi-Fi, electricity backup, and access to the kitchen and lounge included.",
    "Islamabad",
    "G-11",
    "House 14, G-11/4, Islamabad",
    33.695,
    73.0025,
    18000,
    "Room",
    1,
    1,
    "Male",
    ["WiFi", "Furnished", "Electricity Backup", "Kitchen"],
  ],

  [
    15,
    3,
    "Girls Hostel in G-11 Islamabad",
    "Safe and comfortable accommodation for female students and working women. Biometric entry, on-site warden, meal facility, and Wi-Fi included. Located on a well-lit street with easy access to public transport.",
    "Islamabad",
    "G-11",
    "House 22, G-11/1, Islamabad",
    33.6935,
    73.003,
    17000,
    "Shared",
    5,
    3,
    "Female",
    ["WiFi", "Furnished", "Security", "Kitchen", "Laundry"],
  ],

  // ─── F-10 ─────────────────────────────────────────────────────────────────
  [
    18,
    2,
    "Luxury 3-Bed Apartment in F-10 Islamabad",
    "Stunning fully furnished apartment in one of Islamabad's most upscale sectors. Lavishly furnished with Italian sofas, king-size beds, and a chef's kitchen. Marble floors, smart lighting, and a city-view balcony.",
    "Islamabad",
    "F-10",
    "F-10 Markaz, Islamabad",
    33.7077,
    73.0315,
    130000,
    "Apartment",
    3,
    1,
    "Any",
    [
      "WiFi",
      "AC",
      "Parking",
      "Security",
      "Furnished",
      "Balcony",
      "Electricity Backup",
    ],
  ],

  [
    21,
    3,
    "Upper Portion in F-10/3 Islamabad",
    "Charming upper portion of a house on a quiet residential street. 3 bedrooms, a cosy lounge, and a large roof terrace with a view of the Margalla Hills. Fresh paint, new fittings, and generator backup.",
    "Islamabad",
    "F-10",
    "Street 12, F-10/3, Islamabad",
    33.707,
    73.0305,
    68000,
    "Private",
    3,
    1,
    "Any",
    ["Electricity Backup", "Balcony", "Parking"],
  ],

  [
    24,
    2,
    "Professional Room in F-10 Shared House",
    "Spacious room with an attached bath in a well-maintained shared house. All bills included except personal. Just 10 minutes walk from F-10 Markaz. Quiet, professional environment.",
    "Islamabad",
    "F-10",
    "House 8, Street 3, F-10/4, Islamabad",
    33.7083,
    73.032,
    20000,
    "Room",
    1,
    1,
    "Any",
    ["WiFi", "AC", "Furnished", "Electricity Backup", "Kitchen"],
  ],

  [
    27,
    3,
    "Elegant 2-Bed Flat in F-10",
    "Tastefully furnished 2-bedroom flat in a peaceful sector. Both bedrooms are en suite, the lounge is spacious, and the kitchen has been recently renovated. Gated building with parking below.",
    "Islamabad",
    "F-10",
    "Islamabad Residency, F-10/2, Islamabad",
    33.7065,
    73.03,
    75000,
    "Apartment",
    2,
    1,
    "Any",
    ["WiFi", "AC", "Parking", "Security", "Furnished", "Electricity Backup"],
  ],

  // ─── E-11 ─────────────────────────────────────────────────────────────────
  [
    0,
    2,
    "2-Bed Apartment in E-11 Islamabad",
    "Modern 2-bedroom apartment in a newly constructed building. Granite countertops, built-in wardrobes, inverter ACs, and a covered parking space. Very close to Express Highway and Centaurus Mall.",
    "Islamabad",
    "E-11",
    "E-11/2, Near Centaurus, Islamabad",
    33.7188,
    73.001,
    72000,
    "Apartment",
    2,
    1,
    "Any",
    ["WiFi", "AC", "Parking", "Electricity Backup", "Security", "Balcony"],
  ],

  [
    3,
    3,
    "Premium 1-Bed Studio in E-11",
    "Stylish 1-bedroom studio apartment on the 5th floor with a Margalla view. Polished hardwood floors, a custom-built kitchen, and a large wardrobe. Backup generator and broadband included.",
    "Islamabad",
    "E-11",
    "Street 5, E-11/3, Islamabad",
    33.7195,
    73.002,
    52000,
    "Apartment",
    1,
    1,
    "Any",
    ["WiFi", "AC", "Furnished", "Electricity Backup", "Balcony"],
  ],

  [
    6,
    2,
    "Private Room in E-11 Islamabad",
    "Well-furnished private room in a clean shared flat on the 2nd floor. Attached bath, fast internet, UPS backup, and access to a fully equipped kitchen. Suit working professionals.",
    "Islamabad",
    "E-11",
    "House 5, E-11/4, Islamabad",
    33.718,
    73.0005,
    19000,
    "Room",
    1,
    1,
    "Any",
    ["WiFi", "Furnished", "Electricity Backup", "Kitchen"],
  ],

  [
    9,
    3,
    "Luxury Villa Upper Portion in E-11",
    "Upper floor of a premium villa with 4 large bedrooms, a formal lounge, a dining area, and a roof terrace. Built-in wardrobes in all rooms, modular kitchen, and a 2-car garage included.",
    "Islamabad",
    "E-11",
    "Lane 3, E-11/1, Islamabad",
    33.719,
    73.003,
    110000,
    "Private",
    4,
    2,
    "Any",
    ["AC", "Parking", "Security", "Electricity Backup", "Balcony"],
  ],

  // ─── Bahria Town Islamabad ─────────────────────────────────────────────────
  [
    12,
    2,
    "Luxury House in Bahria Town Islamabad",
    "Beautifully furnished 10-marla house in the heart of Bahria Town with access to the community park, mosque, and commercial area. 5 bedrooms, 4 baths, a cinema room, and a solar power system.",
    "Islamabad",
    "Bahria Town",
    "Bahria Town, Phase 8, Islamabad",
    33.5652,
    73.1071,
    160000,
    "House",
    5,
    2,
    "Any",
    ["WiFi", "AC", "Parking", "Security", "Electricity Backup", "Balcony"],
  ],

  [
    15,
    3,
    "Modern Bahria Town Apartment",
    "Contemporary 3-bedroom apartment in Bahria Enclave Tower. The community boasts a rooftop pool, gym, kids' play area, and 24/7 guards. Shops and a mini supermarket are on the ground floor.",
    "Islamabad",
    "Bahria Town",
    "Bahria Enclave, Block A, Islamabad",
    33.566,
    73.1085,
    95000,
    "Apartment",
    3,
    1,
    "Any",
    ["WiFi", "AC", "Parking", "Security", "Electricity Backup", "Balcony"],
  ],

  [
    18,
    2,
    "Semi-Furnished House in Bahria Town",
    "Well-built 7-marla house in a gated community with 24-hour security. 3 bedrooms with built-in wardrobes, a combined lounge and dining room, and a tidy garden. Solar panels provide 10-hour daily backup.",
    "Islamabad",
    "Bahria Town",
    "Bahria Town, Phase 4, Islamabad",
    33.5645,
    73.106,
    120000,
    "House",
    3,
    1,
    "Any",
    ["Parking", "Security", "Electricity Backup"],
  ],

  [
    21,
    3,
    "Bahria Town Furnished Apartment — 2 Bed",
    "Fully furnished 2-bedroom apartment in Bahria Paradise Tower. High-speed internet, inverter ACs, underground parking, and a concierge desk on the ground floor. Minutes from Bahria Grand Mosque.",
    "Islamabad",
    "Bahria Town",
    "Bahria Paradise Tower, Bahria Town, Islamabad",
    33.5658,
    73.108,
    80000,
    "Apartment",
    2,
    1,
    "Any",
    ["WiFi", "AC", "Parking", "Security", "Furnished", "Electricity Backup"],
  ],

  // ─── Blue Area ────────────────────────────────────────────────────────────
  [
    24,
    2,
    "Studio Apartment in Blue Area Islamabad",
    "Serviced studio in a commercial building in the heart of Blue Area. Includes a reception, housekeeping, high-speed internet, and a pantry. Ideal for business travellers or corporate executives.",
    "Islamabad",
    "Blue Area",
    "Jinnah Avenue, Blue Area, Islamabad",
    33.7295,
    73.0935,
    55000,
    "Apartment",
    1,
    1,
    "Any",
    ["WiFi", "AC", "Furnished", "Security", "Electricity Backup"],
  ],

  [
    27,
    3,
    "2-Bed Apartment near Blue Area",
    "Spacious 2-bedroom apartment just 5 minutes from Blue Area's banking district. Modern kitchen, split ACs, and a secure parking spot. Great views of the Shakarparian Hills from the balcony.",
    "Islamabad",
    "Blue Area",
    "F-7 Road, Near Blue Area, Islamabad",
    33.73,
    73.0945,
    85000,
    "Apartment",
    2,
    1,
    "Any",
    ["WiFi", "AC", "Parking", "Security", "Balcony", "Electricity Backup"],
  ],

  [
    0,
    2,
    "Executive Room near Blue Area",
    "Private en-suite room in a managed serviced residence, 8 minutes from the Islamabad High Court and central banks. Daily housekeeping, breakfast included, fast Wi-Fi, and UPS backup.",
    "Islamabad",
    "Blue Area",
    "Khayaban-e-Suharwardy, Islamabad",
    33.7289,
    73.092,
    28000,
    "Room",
    1,
    1,
    "Any",
    ["WiFi", "AC", "Furnished", "Security", "Electricity Backup"],
  ],

  [
    3,
    3,
    "Apartment with Margalla View, Blue Area",
    "Premium apartment in a prestige high-rise above Blue Area. Floor-to-ceiling windows with a breathtaking Margalla Hills view. Chef's kitchen, smart home controls, and private elevator lobby.",
    "Islamabad",
    "Blue Area",
    "Centaurus Vicinity, Blue Area, Islamabad",
    33.7305,
    73.0955,
    120000,
    "Apartment",
    3,
    1,
    "Any",
    [
      "WiFi",
      "AC",
      "Parking",
      "Security",
      "Furnished",
      "Balcony",
      "Electricity Backup",
    ],
  ],

  // ═══════════════════════════════════════════════════════════ RAWALPINDI ══
  // ─── Saddar ───────────────────────────────────────────────────────────────
  [
    6,
    9,
    "Furnished Room in Saddar Rawalpindi",
    "Clean furnished room with attached bath in a residential colony near Saddar market. Daily housekeeping, free Wi-Fi, and electricity backup via UPS included. Close to major shopping centres and Rawalpindi railway station.",
    "Rawalpindi",
    "Saddar",
    "Near Saddar Bazaar, Rawalpindi",
    33.5939,
    73.0441,
    13000,
    "Room",
    1,
    1,
    "Male",
    ["WiFi", "Furnished", "Electricity Backup", "Security"],
  ],

  [
    9,
    9,
    "Shared Accommodation near Saddar",
    "Budget accommodation for students and junior employees. Shared rooms, common kitchen, laundry facility, and a rooftop seating area. Close to all conveniences including a medical store, ATM, and bus stops.",
    "Rawalpindi",
    "Saddar",
    "Near Lal Kurti Bazaar, Saddar, Rawalpindi",
    33.5945,
    73.0435,
    9000,
    "Shared",
    6,
    4,
    "Male",
    ["WiFi", "Kitchen", "Laundry", "Electricity Backup"],
  ],

  [
    12,
    9,
    "1-Bed Apartment near Saddar Rawalpindi",
    "Compact 1-bedroom apartment on a busy street with easy access to public transport. Fitted kitchen, tiled bathroom, inverter AC, and building-wide CCTV. Suitable for a couple or a single professional.",
    "Rawalpindi",
    "Saddar",
    "Murree Road, Saddar, Rawalpindi",
    33.5931,
    73.045,
    32000,
    "Apartment",
    1,
    1,
    "Any",
    ["AC", "Kitchen", "Electricity Backup", "Security"],
  ],

  // ─── Satellite Town ───────────────────────────────────────────────────────
  [
    15,
    9,
    "2-Bed Apartment in Satellite Town",
    "Well-maintained 2-bedroom apartment in a peaceful residential block. Split ACs, tiled kitchen, and a neat bathroom with geysers. Covered parking and 24/7 WASA supply. Close to PWD housing society.",
    "Rawalpindi",
    "Satellite Town",
    "Block D, Satellite Town, Rawalpindi",
    33.5898,
    73.0703,
    48000,
    "Apartment",
    2,
    1,
    "Any",
    ["AC", "Parking", "Electricity Backup", "Security"],
  ],

  [
    18,
    9,
    "Upper Portion in Satellite Town Rawalpindi",
    "Comfortable upper portion of a double-story house on a quiet street. 2 bedrooms, a large lounge, a modern kitchen, and rooftop access. Fresh paint and new plumbing throughout.",
    "Rawalpindi",
    "Satellite Town",
    "Block B, Satellite Town, Rawalpindi",
    33.5905,
    73.071,
    44000,
    "Private",
    2,
    1,
    "Any",
    ["Electricity Backup", "Parking", "Balcony"],
  ],

  [
    21,
    9,
    "Furnished Flat for Professionals in Satellite Town",
    "Modern furnished flat ideal for a small family or working couple. Master bedroom with attached bath, a guest room, open-plan kitchen, and a lounge. Fibre internet and inverter AC in the master bedroom.",
    "Rawalpindi",
    "Satellite Town",
    "Street 3, Satellite Town, Rawalpindi",
    33.5892,
    73.0698,
    55000,
    "Apartment",
    2,
    1,
    "Any",
    ["WiFi", "AC", "Furnished", "Electricity Backup", "Parking"],
  ],

  // ─── Bahria Town Rawalpindi ────────────────────────────────────────────────
  [
    24,
    9,
    "Bahria Town House for Rent — Rawalpindi",
    "Elegant 5-marla house in the prestigious Bahria Town community. Features 3 bedrooms, 2 baths, a drawing room, a kitchen, and a single-car garage. 24/7 security, park access, and solar backup.",
    "Rawalpindi",
    "Bahria Town",
    "Bahria Town, Rawalpindi",
    33.5203,
    73.095,
    110000,
    "House",
    3,
    1,
    "Any",
    ["Parking", "Security", "Electricity Backup", "Balcony"],
  ],

  [
    27,
    9,
    "Bahria Town Apartment — 2 Bed Furnished",
    "Beautifully furnished 2-bedroom apartment in Bahria Heights. Access to community gym, swimming pool, and park. Walking distance from Bahria Town commercial area and schools.",
    "Rawalpindi",
    "Bahria Town",
    "Bahria Heights, Rawalpindi",
    33.521,
    73.096,
    75000,
    "Apartment",
    2,
    1,
    "Any",
    ["WiFi", "AC", "Parking", "Security", "Furnished", "Electricity Backup"],
  ],

  [
    0,
    9,
    "Bahria Town 7-Marla House for Rent",
    "Spacious 7-marla house in Bahria Town with 4 bedrooms, a family lounge, drawing room, and a double garage. Solar power for 15 hours daily, 24/7 security, and access to a private park.",
    "Rawalpindi",
    "Bahria Town",
    "Phase 7, Bahria Town, Rawalpindi",
    33.5195,
    73.094,
    140000,
    "House",
    4,
    2,
    "Any",
    ["Parking", "Security", "Electricity Backup", "Balcony"],
  ],

  // ─── Gulraiz Housing Scheme ────────────────────────────────────────────────
  [
    3,
    9,
    "Room in Gulraiz Housing Scheme",
    "Single furnished room available in a shared house in Gulraiz. Wi-Fi, electricity backup, and a shared kitchen are included. Just 10 minutes from Rawalpindi Saddar by Careem/rickshaw.",
    "Rawalpindi",
    "Gulraiz Housing Scheme",
    "Block 2, Gulraiz Housing Scheme, Rawalpindi",
    33.5863,
    73.051,
    12000,
    "Room",
    1,
    1,
    "Male",
    ["WiFi", "Electricity Backup", "Kitchen"],
  ],

  [
    6,
    9,
    "Shared Hostel in Gulraiz Rawalpindi",
    "Clean, affordable hostel rooms for students and workers. 3 meals a day, laundry, Wi-Fi, and a prayer room are provided. Strict management with CCTV throughout.",
    "Rawalpindi",
    "Gulraiz Housing Scheme",
    "Near CMA Complex, Gulraiz, Rawalpindi",
    33.587,
    73.0518,
    10000,
    "Shared",
    10,
    5,
    "Male",
    ["WiFi", "Kitchen", "Laundry", "Security", "Electricity Backup"],
  ],

  [
    9,
    9,
    "1-Bed Apartment in Gulraiz",
    "Affordable 1-bedroom apartment in a quiet area. Split AC, tiled bathroom, a compact kitchen with a gas connection, and a sunny balcony. Parking spot available at an extra PKR 2000 per month.",
    "Rawalpindi",
    "Gulraiz Housing Scheme",
    "Block A, Gulraiz Phase 2, Rawalpindi",
    33.5856,
    73.0505,
    30000,
    "Apartment",
    1,
    1,
    "Any",
    ["AC", "Kitchen", "Electricity Backup", "Balcony"],
  ],

  // ─── Commercial Market ────────────────────────────────────────────────────
  [
    12,
    9,
    "Shared Room near Commercial Market Rawalpindi",
    "Budget-friendly shared room for working men near Commercial Market. 3 beds per room, common bathrooms, fast Wi-Fi, and all meals available. Convenient for daily commuters.",
    "Rawalpindi",
    "Commercial Market",
    "Near Commercial Market, Rawalpindi",
    33.5832,
    73.0538,
    8500,
    "Shared",
    8,
    5,
    "Male",
    ["WiFi", "Kitchen", "Laundry", "Electricity Backup"],
  ],

  [
    15,
    9,
    "Single Room near Commercial Market",
    "Neat single room with a private bathroom in a residential building. Electricity backup, unlimited internet, and a shared kitchen. Very close to the main bus route and local markets.",
    "Rawalpindi",
    "Commercial Market",
    "Haider Road, Commercial Market, Rawalpindi",
    33.5838,
    73.0545,
    11500,
    "Room",
    1,
    1,
    "Male",
    ["WiFi", "Electricity Backup", "Kitchen"],
  ],

  // ══════════════════════════════════════════════════════════════ KARACHI ══
  // ─── Gulshan-e-Iqbal ──────────────────────────────────────────────────────
  [
    18,
    4,
    "2-Bed Apartment in Gulshan-e-Iqbal",
    "Well-maintained 2-bedroom apartment in Block 13D. Tiled throughout, split ACs in both rooms, a separate kitchen with gas, and dedicated parking. 24/7 generator backup in the building.",
    "Karachi",
    "Gulshan-e-Iqbal",
    "Block 13-D, Gulshan-e-Iqbal, Karachi",
    24.9272,
    67.1127,
    52000,
    "Apartment",
    2,
    1,
    "Any",
    ["AC", "Parking", "Electricity Backup", "Security", "Kitchen"],
  ],

  [
    21,
    5,
    "Upper Portion in Gulshan-e-Iqbal",
    "3-bedroom upper portion with a rooftop terrace, a drawing-dining area, and an updated kitchen. Separate entrance, 1.5-hour load-shedding area, and a good water supply. Easy access to Nagan Chowrangi Metro.",
    "Karachi",
    "Gulshan-e-Iqbal",
    "Block 10, Gulshan-e-Iqbal, Karachi",
    24.928,
    67.1132,
    58000,
    "Private",
    3,
    1,
    "Any",
    ["Electricity Backup", "Balcony", "Kitchen", "Parking"],
  ],

  [
    24,
    4,
    "Furnished Room in Gulshan-e-Iqbal",
    "Clean furnished room with an attached bathroom in a shared house near Gulshan Chowrangi. Wi-Fi, UPS backup, and a shared kitchen provided. Peaceful area suitable for students.",
    "Karachi",
    "Gulshan-e-Iqbal",
    "Block 14, Gulshan-e-Iqbal, Karachi",
    24.9265,
    67.112,
    15000,
    "Room",
    1,
    1,
    "Male",
    ["WiFi", "Furnished", "Electricity Backup", "Kitchen"],
  ],

  [
    27,
    5,
    "3-Bed Apartment in Gulshan-e-Iqbal Block 7",
    "Spacious 3-bedroom apartment in one of Karachi's most sought-after localities. Large lounge, a separate dining area, a store room, and a servant quarter. Very close to the Aga Khan Hospital.",
    "Karachi",
    "Gulshan-e-Iqbal",
    "Block 7, Gulshan-e-Iqbal, Karachi",
    24.9278,
    67.114,
    72000,
    "Apartment",
    3,
    1,
    "Any",
    ["AC", "Parking", "Security", "Electricity Backup", "Kitchen"],
  ],

  // ─── DHA Karachi ──────────────────────────────────────────────────────────
  [
    0,
    5,
    "Luxury 4-Bed Bungalow in DHA Phase 6",
    "Stunning 500 sq-yard bungalow with a beautifully landscaped garden, a private swimming pool, and a home cinema. 4 en-suite bedrooms, a formal lounge, and a triple garage. 24/7 DHA security.",
    "Karachi",
    "DHA Phase 6",
    "Street 7, Phase 6, DHA, Karachi",
    24.8067,
    67.065,
    350000,
    "House",
    4,
    2,
    "Any",
    [
      "WiFi",
      "AC",
      "Parking",
      "Security",
      "Furnished",
      "Balcony",
      "Electricity Backup",
    ],
  ],

  [
    3,
    4,
    "3-Bed Apartment in DHA Phase 2",
    "Bright and airy 3-bedroom apartment in a prestigious DHA building. Modern kitchen with built-in hob and oven, marble floors, and a sea-facing balcony. Gym and swimming pool access for residents.",
    "Karachi",
    "DHA Phase 2",
    "Khayaban-e-Sehar, DHA Phase 2, Karachi",
    24.8075,
    67.0658,
    130000,
    "Apartment",
    3,
    1,
    "Any",
    [
      "WiFi",
      "AC",
      "Parking",
      "Security",
      "Furnished",
      "Balcony",
      "Electricity Backup",
    ],
  ],

  [
    6,
    5,
    "5-Marla House in DHA Phase 5",
    "Excellent 5-marla house with 3 bedrooms, 2 baths, and a cosy lounge. Fully tiled, new plumbing, and a well-maintained kitchen garden. DHA security, regular garbage collection, and good water supply.",
    "Karachi",
    "DHA Phase 5",
    "Street 4, Phase 5, DHA, Karachi",
    24.806,
    67.0645,
    155000,
    "House",
    3,
    1,
    "Any",
    ["Parking", "Security", "Electricity Backup"],
  ],

  [
    9,
    4,
    "Furnished 2-Bed in DHA Phase 8",
    "Contemporary fully furnished 2-bedroom apartment on the 8th floor with panoramic sea views. Smart home features, inverter ACs, a chef's kitchen, and two dedicated underground parking spots.",
    "Karachi",
    "DHA Phase 8",
    "Seaview Avenue, DHA Phase 8, Karachi",
    24.8055,
    67.064,
    110000,
    "Apartment",
    2,
    1,
    "Any",
    [
      "WiFi",
      "AC",
      "Parking",
      "Security",
      "Furnished",
      "Balcony",
      "Electricity Backup",
    ],
  ],

  // ─── Clifton ──────────────────────────────────────────────────────────────
  [
    12,
    5,
    "Premium Sea-View Apartment in Clifton",
    "Breathtaking 3-bedroom apartment with direct views of the Arabian Sea. Floor-to-ceiling glass, imported marble floors, a designer kitchen, and private lift access. Concierge, valet parking, and a rooftop lounge.",
    "Karachi",
    "Clifton",
    "Clifton Block 5, Karachi",
    24.8139,
    67.0305,
    200000,
    "Apartment",
    3,
    1,
    "Any",
    [
      "WiFi",
      "AC",
      "Parking",
      "Security",
      "Furnished",
      "Balcony",
      "Electricity Backup",
    ],
  ],

  [
    15,
    4,
    "2-Bed Flat in Clifton Block 2",
    "Well-maintained 2-bedroom flat with a sea breeze facing balcony. Tiled throughout, split ACs, a compact yet functional kitchen, and a secure parking bay. Walking distance to Clifton Beach.",
    "Karachi",
    "Clifton",
    "Block 2, Clifton, Karachi",
    24.8145,
    67.0312,
    88000,
    "Apartment",
    2,
    1,
    "Any",
    ["AC", "Parking", "Security", "Balcony", "Electricity Backup"],
  ],

  [
    18,
    5,
    "Executive Room in Clifton Karachi",
    "Elegant room in a managed executive residence. En-suite bathroom, high-speed fibre internet, housekeeping daily, and a shared premium kitchen lounge area. Ideal for expats and senior professionals.",
    "Karachi",
    "Clifton",
    "Clifton Block 9, Karachi",
    24.8132,
    67.0298,
    35000,
    "Room",
    1,
    1,
    "Any",
    ["WiFi", "AC", "Furnished", "Security", "Electricity Backup", "Kitchen"],
  ],

  [
    21,
    4,
    "Luxury Villa Lower Portion in Clifton",
    "Grand lower portion of a sea-facing villa. 4 bedrooms, a huge drawing room, a formal dining area, and a private garden with outdoor seating. Separate servant's quarter and double garage included.",
    "Karachi",
    "Clifton",
    "Block 8, Clifton, Karachi",
    24.813,
    67.032,
    180000,
    "Private",
    4,
    2,
    "Any",
    ["WiFi", "AC", "Parking", "Security", "Electricity Backup", "Balcony"],
  ],

  // ─── PECHS ────────────────────────────────────────────────────────────────
  [
    24,
    5,
    "2-Bed Apartment in PECHS Block 2",
    "Comfortable 2-bedroom apartment in a well-maintained building in PECHS. Separate kitchen, gas and electricity connections, CCTV in common areas, and a covered parking space. Close to Nursery flyover.",
    "Karachi",
    "PECHS",
    "Block 2, PECHS, Karachi",
    24.8736,
    67.062,
    58000,
    "Apartment",
    2,
    1,
    "Any",
    ["AC", "Parking", "Security", "Electricity Backup", "Kitchen"],
  ],

  [
    27,
    4,
    "Single Furnished Room in PECHS",
    "Neat furnished room in a PECHS house shared with professionals. Attached bath, split AC, Wi-Fi, and UPS backup. Very close to Tariq Road shopping area and Ayesha Manzil bus stop.",
    "Karachi",
    "PECHS",
    "Block 6, PECHS, Karachi",
    24.8742,
    67.0628,
    18000,
    "Room",
    1,
    1,
    "Any",
    ["WiFi", "AC", "Furnished", "Electricity Backup"],
  ],

  [
    0,
    5,
    "Upper Portion in PECHS Block 3",
    "Spacious upper portion with 3 bedrooms, 2 baths, and a sunny terrace. Separate entrance, new paint, and freshly tiled kitchen. A short walk from the main commercial strip.",
    "Karachi",
    "PECHS",
    "Block 3, PECHS, Karachi",
    24.873,
    67.0615,
    68000,
    "Private",
    3,
    1,
    "Any",
    ["Electricity Backup", "Balcony", "Parking", "Kitchen"],
  ],

  [
    3,
    4,
    "3-Bed Apartment in PECHS Block 6",
    "Spacious 3-bedroom apartment with a wide lounge and a large balcony in a prestigious PECHS building. Modern kitchen, gas-powered geyser, and intercom. Building has a backup generator.",
    "Karachi",
    "PECHS",
    "Block 6, PECHS, Karachi",
    24.8739,
    67.0624,
    76000,
    "Apartment",
    3,
    1,
    "Any",
    ["AC", "Parking", "Security", "Electricity Backup", "Balcony", "Kitchen"],
  ],

  // ─── North Nazimabad ──────────────────────────────────────────────────────
  [
    6,
    5,
    "Room in North Nazimabad for Students",
    "Clean furnished room in a shared student house near North Nazimabad. Fast internet, 24/7 electricity backup, and a common kitchen. Close to multiple coaching centres and a medical store.",
    "Karachi",
    "North Nazimabad",
    "Block L, North Nazimabad, Karachi",
    24.9391,
    67.0453,
    12000,
    "Room",
    1,
    1,
    "Male",
    ["WiFi", "Furnished", "Electricity Backup", "Kitchen"],
  ],

  [
    9,
    4,
    "Shared Boys Accommodation in North Nazimabad",
    "Managed hostel for working males near North Nazimabad Square. All meals, laundry, Wi-Fi, and electricity included in one monthly fee. CCTV throughout and a professional warden on duty.",
    "Karachi",
    "North Nazimabad",
    "Block F, North Nazimabad, Karachi",
    24.9398,
    67.046,
    11000,
    "Shared",
    8,
    4,
    "Male",
    ["WiFi", "Kitchen", "Laundry", "Security", "Electricity Backup"],
  ],

  [
    12,
    5,
    "1-Bed Flat in North Nazimabad",
    "Affordable 1-bedroom flat ideal for a couple or single person. Tiled throughout, compact kitchen with a gas connection, a split AC, and a sunny balcony. Close to a Metro Bus station.",
    "Karachi",
    "North Nazimabad",
    "Block H, North Nazimabad, Karachi",
    24.9385,
    67.0448,
    36000,
    "Apartment",
    1,
    1,
    "Any",
    ["AC", "Electricity Backup", "Balcony", "Kitchen"],
  ],

  [
    15,
    4,
    "2-Bed Apartment in North Nazimabad Block N",
    "Great-value 2-bedroom apartment on the 4th floor. Separate lounge and dining area, gas water heater, inverter AC, and dedicated parking. Regular water supply with 2000-litre overhead tank.",
    "Karachi",
    "North Nazimabad",
    "Block N, North Nazimabad, Karachi",
    24.938,
    67.0445,
    48000,
    "Apartment",
    2,
    1,
    "Any",
    ["AC", "Parking", "Electricity Backup", "Kitchen"],
  ],

  // ══════════════════════════════════════════════════════════════ MULTAN ══
  // ─── Gulgasht Colony ──────────────────────────────────────────────────────
  [
    18,
    6,
    "2-Bed Apartment in Gulgasht Colony Multan",
    "Neat and clean 2-bedroom apartment in a residential building in Gulgasht. Split ACs, tiled kitchen, and a generator backup system. Close to Gulgasht market and Multan Institute of Technology.",
    "Multan",
    "Gulgasht Colony",
    "Block B, Gulgasht Colony, Multan",
    30.2029,
    71.4351,
    42000,
    "Apartment",
    2,
    1,
    "Any",
    ["AC", "Kitchen", "Electricity Backup", "Parking"],
  ],

  [
    21,
    6,
    "Studio Flat in Gulgasht Multan",
    "Affordable studio flat suitable for a working professional. Compact kitchen, tiled bathroom, split AC, and a UPS for daily essentials. Close to public transport and local eateries.",
    "Multan",
    "Gulgasht Colony",
    "Gulgasht Chowk, Multan",
    30.2035,
    71.4358,
    28000,
    "Apartment",
    1,
    1,
    "Any",
    ["AC", "Kitchen", "Electricity Backup"],
  ],

  [
    24,
    6,
    "Boys Hostel Room in Gulgasht Multan",
    "Well-managed hostel for students and workers with clean rooms. Meals twice a day, laundry service, Wi-Fi, and 24-hour electricity via solar and UPS. Close to Bahauddin Zakariya University.",
    "Multan",
    "Gulgasht Colony",
    "Near BZU, Gulgasht, Multan",
    30.2022,
    71.4342,
    10000,
    "Shared",
    6,
    4,
    "Male",
    ["WiFi", "Kitchen", "Laundry", "Electricity Backup", "Security"],
  ],

  // ─── Bosan Road ───────────────────────────────────────────────────────────
  [
    27,
    6,
    "Family House on Bosan Road Multan",
    "Spacious 7-marla house with 4 bedrooms, a drawing-dining room, and a neat kitchen. Solar panel system for 12-hour backup, a carport for 2 cars, and a shaded front lawn.",
    "Multan",
    "Bosan Road",
    "Plot 22, Bosan Road, Multan",
    30.2132,
    71.3972,
    110000,
    "House",
    4,
    2,
    "Any",
    ["Parking", "Electricity Backup", "Security", "Balcony"],
  ],

  [
    0,
    6,
    "5-Marla House on Bosan Road Multan",
    "Solid construction 5-marla residential house with 3 bedrooms, 2 baths, a full kitchen, and a small yard. Good road access, a stable electricity zone, and a water boring on the plot.",
    "Multan",
    "Bosan Road",
    "Block D, Bosan Road Housing Scheme, Multan",
    30.2126,
    71.3965,
    82000,
    "House",
    3,
    1,
    "Any",
    ["Parking", "Electricity Backup"],
  ],

  [
    3,
    6,
    "Upper Portion on Bosan Road",
    "Nice upper portion of a newly built house. 2 bedrooms with attached baths, a stylish lounge, and a large terrace. Separate gas and electricity meters, with a UPS system for fans and lights.",
    "Multan",
    "Bosan Road",
    "Street 5, Bosan Road, Multan",
    30.2138,
    71.398,
    52000,
    "Private",
    2,
    2,
    "Any",
    ["Electricity Backup", "Balcony", "Kitchen"],
  ],

  // ─── Cantt Multan ─────────────────────────────────────────────────────────
  [
    6,
    7,
    "Luxury House in Multan Cantt",
    "Beautiful 10-marla house in the green and peaceful Cantt area. 5 bedrooms, a large drawing room, a dining area, and a spacious lawn. The area has a 0% load-shedding record and excellent road infrastructure.",
    "Multan",
    "Cantt",
    "Cantt Housing Scheme, Multan",
    30.1742,
    71.5076,
    160000,
    "House",
    5,
    2,
    "Any",
    ["Parking", "Security", "Electricity Backup", "Balcony"],
  ],

  [
    9,
    6,
    "2-Bed Apartment in Multan Cantt",
    "Well-built apartment near the main Cantt commercial area. 2 bedrooms with fitted wardrobes, a well-sized lounge, and a balcony. Generator backup and a rooftop water tank ensure uninterrupted supply.",
    "Multan",
    "Cantt",
    "Near Mall Road, Cantt, Multan",
    30.175,
    71.5083,
    56000,
    "Apartment",
    2,
    1,
    "Any",
    ["AC", "Parking", "Electricity Backup", "Balcony", "Kitchen"],
  ],

  [
    12,
    7,
    "Private Portion in Multan Cantt",
    "Semi-furnished private portion with 3 bedrooms, 2 baths, and a wide lounge. Back garden with an outdoor seating area. 24/7 power supply via DHA-maintained infrastructure.",
    "Multan",
    "Cantt",
    "Cantt Area, Multan",
    30.1736,
    71.5068,
    72000,
    "Private",
    3,
    1,
    "Any",
    ["Electricity Backup", "Parking", "Balcony"],
  ],

  // ─── Shah Rukn-e-Alam ─────────────────────────────────────────────────────
  [
    15,
    6,
    "Room near Shah Rukn-e-Alam Multan",
    "Budget furnished room for a single male near the holy shrine area. Attached washroom, common prayer area, 24/7 electricity from UPS, and a shared kitchen. Very peaceful locality.",
    "Multan",
    "Shah Rukn-e-Alam",
    "Near Hazrat Shah Rukn-e-Alam, Multan",
    30.1962,
    71.4758,
    11000,
    "Room",
    1,
    1,
    "Male",
    ["WiFi", "Electricity Backup", "Kitchen"],
  ],

  [
    18,
    6,
    "Shared Hostel near Shah Rukn-e-Alam",
    "Clean shared hostel rooms near the shrine. Meals, laundry, and Wi-Fi are included. Managed by a reputable family. Excellent transport links to BZU and Bahauddin Zikriya Medical University.",
    "Multan",
    "Shah Rukn-e-Alam",
    "Shrine Road, Multan",
    30.1955,
    71.475,
    9000,
    "Shared",
    8,
    4,
    "Male",
    ["WiFi", "Kitchen", "Laundry", "Electricity Backup"],
  ],

  [
    21,
    7,
    "1-Bed Apartment near Shah Rukn-e-Alam",
    "Decent 1-bedroom apartment with a separate kitchen, a tiled bath, and a small balcony. Located on a main road with regular bus service. Generator backup available for 8 hours daily.",
    "Multan",
    "Shah Rukn-e-Alam",
    "Shah Rukn Road, Multan",
    30.1968,
    71.4765,
    30000,
    "Apartment",
    1,
    1,
    "Any",
    ["Electricity Backup", "Balcony", "Kitchen"],
  ],

  // ══════════════════════════════════════════════════════════ FAISALABAD ══
  // ─── D Ground ─────────────────────────────────────────────────────────────
  [
    24,
    7,
    "2-Bed Apartment near D Ground Faisalabad",
    "Well-maintained 2-bedroom apartment in a central location near D Ground. Both bedrooms have split ACs, the kitchen has a complete gas connection, and the building has a diesel generator for power cuts.",
    "Faisalabad",
    "D Ground",
    "Near D Ground, Faisalabad",
    31.4218,
    73.1077,
    44000,
    "Apartment",
    2,
    1,
    "Any",
    ["AC", "Kitchen", "Electricity Backup", "Parking"],
  ],

  [
    27,
    7,
    "1-Bed Flat near D Ground",
    "Budget-friendly 1-bedroom flat for a single occupant. Clean bathroom, compact kitchen, and a UPS for lights and fans during load-shedding. Walking distance to Ghanta Ghar and city buses.",
    "Faisalabad",
    "D Ground",
    "D Ground Road, Faisalabad",
    31.4225,
    73.1083,
    28000,
    "Apartment",
    1,
    1,
    "Any",
    ["Electricity Backup", "Kitchen"],
  ],

  [
    0,
    7,
    "Furnished Room near D Ground",
    "Neat furnished room available immediately in a shared accommodation near D Ground. Internet, electricity backup, and kitchen access included. Ideal for students at GC University or University of Agriculture.",
    "Faisalabad",
    "D Ground",
    "Near GCU, D Ground, Faisalabad",
    31.4211,
    73.107,
    13000,
    "Room",
    1,
    1,
    "Male",
    ["WiFi", "Furnished", "Electricity Backup", "Kitchen"],
  ],

  // ─── Peoples Colony ───────────────────────────────────────────────────────
  [
    3,
    8,
    "5-Marla House in Peoples Colony Faisalabad",
    "Classic 5-marla house with 3 bedrooms, a drawing room, a kitchen, and a small garden. The area has minimal load-shedding with UPS backup. Close to Peoples Colony Government Hospital.",
    "Faisalabad",
    "Peoples Colony",
    "Block A, Peoples Colony, Faisalabad",
    31.4535,
    73.1057,
    78000,
    "House",
    3,
    1,
    "Any",
    ["Parking", "Electricity Backup"],
  ],

  [
    6,
    7,
    "2-Bed Apartment in Peoples Colony",
    "Comfortable 2-bedroom apartment on the 3rd floor of a tidy building. Gas connection, split ACs in both bedrooms, and a balcony with a nice street view. Close to Susan Road and Al-Fatah store.",
    "Faisalabad",
    "Peoples Colony",
    "Block C, Peoples Colony, Faisalabad",
    31.4542,
    73.1064,
    46000,
    "Apartment",
    2,
    1,
    "Any",
    ["AC", "Electricity Backup", "Balcony", "Kitchen"],
  ],

  [
    9,
    8,
    "Upper Portion in Peoples Colony",
    "Charming upper portion with 2 bedrooms, a lounge, and a sunny rooftop. Newly painted walls, clean tiled floors, and a gas water heater. Monthly rent is all-inclusive of maintenance charges.",
    "Faisalabad",
    "Peoples Colony",
    "Street 12, Peoples Colony, Faisalabad",
    31.4528,
    73.105,
    42000,
    "Private",
    2,
    1,
    "Any",
    ["Electricity Backup", "Balcony", "Kitchen"],
  ],

  // ─── Madina Town ──────────────────────────────────────────────────────────
  [
    12,
    7,
    "Room in Madina Town Faisalabad",
    "Single furnished room in a shared house in Madina Town. Attached bath, power backup, free Wi-Fi, and daily cleaning. Close to Madina Town commercial market and a Punjab University campus.",
    "Faisalabad",
    "Madina Town",
    "Near Madina Chowk, Madina Town, Faisalabad",
    31.4194,
    73.0875,
    12500,
    "Room",
    1,
    1,
    "Male",
    ["WiFi", "Furnished", "Electricity Backup", "Kitchen"],
  ],

  [
    15,
    8,
    "Shared Boys Hostel in Madina Town",
    "Affordable student hostel with double-occupancy furnished rooms. 3 meals a day, laundry, and Wi-Fi all included. Solar panels provide 16 hours of electricity daily. Close to NFC IET University.",
    "Faisalabad",
    "Madina Town",
    "Block E, Madina Town, Faisalabad",
    31.42,
    73.0882,
    9000,
    "Shared",
    10,
    6,
    "Male",
    ["WiFi", "Kitchen", "Laundry", "Electricity Backup", "Security"],
  ],

  [
    18,
    7,
    "1-Bed Apartment in Madina Town",
    "Well-maintained 1-bedroom apartment ideal for a young professional. Tiled kitchen, attached bath with geysers, split AC, and balcony with a street view. Near Madina Town bus terminal.",
    "Faisalabad",
    "Madina Town",
    "Madina Town, Faisalabad",
    31.4188,
    73.0869,
    32000,
    "Apartment",
    1,
    1,
    "Any",
    ["AC", "Electricity Backup", "Balcony", "Kitchen"],
  ],

  // ─── Susan Road ───────────────────────────────────────────────────────────
  [
    21,
    8,
    "2-Bed Apartment on Susan Road Faisalabad",
    "Modern 2-bedroom apartment in a new building on the main Susan Road artery. Open-plan lounge and dining, a large kitchen with a gas range, split ACs, and rooftop access.",
    "Faisalabad",
    "Susan Road",
    "Susan Road, Faisalabad",
    31.4778,
    73.0976,
    50000,
    "Apartment",
    2,
    1,
    "Any",
    ["AC", "Parking", "Electricity Backup", "Balcony", "Kitchen"],
  ],

  [
    24,
    7,
    "Upper Portion on Susan Road",
    "Large upper portion with 3 bedrooms, 2 baths, a wide lounge, and a rooftop terrace. Separate entrance, all connections independent, and a dedicated water pump.",
    "Faisalabad",
    "Susan Road",
    "Near Susan Road, Faisalabad",
    31.4784,
    73.0983,
    58000,
    "Private",
    3,
    1,
    "Any",
    ["Electricity Backup", "Balcony", "Kitchen", "Parking"],
  ],

  [
    27,
    8,
    "Budget Room on Susan Road",
    "Affordable room for a single professional near Susan Road. Attached bath, Wi-Fi, UPS for lights and fan, and access to a shared kitchen. Close to Faisalabad Airport and Nishat Mills.",
    "Faisalabad",
    "Susan Road",
    "Susan Road, Near Airport, Faisalabad",
    31.477,
    73.0969,
    12000,
    "Room",
    1,
    1,
    "Male",
    ["WiFi", "Electricity Backup", "Kitchen"],
  ],

  // ══════════════════════════════════════════════════════════════ PESHAWAR ══
  // ─── Hayatabad ────────────────────────────────────────────────────────────
  [
    0,
    8,
    "Modern House in Hayatabad Phase 3",
    "Well-constructed 5-marla house in the well-planned Hayatabad township. 3 bedrooms, 2 baths, a drawing-dining room, and a rooftop. Solar power provides a reliable backup. Good road infrastructure and parks nearby.",
    "Peshawar",
    "Hayatabad",
    "Phase 3, Hayatabad, Peshawar",
    33.985,
    71.4592,
    95000,
    "House",
    3,
    1,
    "Any",
    ["Parking", "Security", "Electricity Backup", "Balcony"],
  ],

  [
    3,
    8,
    "2-Bed Apartment in Hayatabad Phase 6",
    "Comfortable 2-bedroom apartment in a well-maintained building in Hayatabad Phase 6. Split ACs, tiled kitchen, balcony with mountain views, and a generator in the building. Close to supermarkets and schools.",
    "Peshawar",
    "Hayatabad",
    "Phase 6, Hayatabad, Peshawar",
    33.9857,
    71.46,
    56000,
    "Apartment",
    2,
    1,
    "Any",
    ["AC", "Electricity Backup", "Balcony", "Kitchen", "Parking"],
  ],

  [
    6,
    8,
    "7-Marla House in Hayatabad Phase 1",
    "Spacious 7-marla house with 4 bedrooms, a formal lounge, drawing room, and a garage for 1 car. Solar panels for 10-hour daily backup. A calm, family-oriented locality in Peshawar's best township.",
    "Peshawar",
    "Hayatabad",
    "Phase 1, Hayatabad, Peshawar",
    33.9843,
    71.4585,
    140000,
    "House",
    4,
    2,
    "Any",
    ["Parking", "Security", "Electricity Backup"],
  ],

  // ─── University Road ──────────────────────────────────────────────────────
  [
    9,
    8,
    "Room near University of Peshawar",
    "Budget furnished room for male students near the University of Peshawar. Wi-Fi, electricity backup, and a shared kitchen included. Just 5 minutes on foot from the university main gate.",
    "Peshawar",
    "University Road",
    "Near University of Peshawar, University Road",
    34.0025,
    71.542,
    11000,
    "Room",
    1,
    1,
    "Male",
    ["WiFi", "Furnished", "Electricity Backup", "Kitchen"],
  ],

  [
    12,
    8,
    "Shared Hostel near University Road Peshawar",
    "Well-run student hostel near Agricultural University. 3 meals per day, laundry, internet, and 18-hour electricity backup. Clean and secure with CCTV and an on-site warden.",
    "Peshawar",
    "University Road",
    "University Road, Peshawar",
    34.0032,
    71.5428,
    9500,
    "Shared",
    12,
    6,
    "Male",
    ["WiFi", "Kitchen", "Laundry", "Security", "Electricity Backup"],
  ],

  [
    15,
    8,
    "1-Bed Flat near University Road",
    "Neat 1-bedroom flat on the 2nd floor of a residential building. Compact kitchen with a gas connection, split AC, and a covered balcony. 5 minutes from Peshawar Motorway interchange.",
    "Peshawar",
    "University Road",
    "Near Ring Road, University Road, Peshawar",
    34.0019,
    71.5414,
    35000,
    "Apartment",
    1,
    1,
    "Any",
    ["AC", "Electricity Backup", "Balcony", "Kitchen"],
  ],

  // ─── Saddar Peshawar ──────────────────────────────────────────────────────
  [
    18,
    8,
    "Shared Room near Saddar Peshawar",
    "Budget shared accommodation for working males near Saddar Bazaar. Double-occupancy rooms with bunk beds, a common kitchen, and a Wi-Fi connection. Very close to local transport hubs.",
    "Peshawar",
    "Saddar",
    "Near Chowk Yadgar, Saddar, Peshawar",
    34.001,
    71.5642,
    8500,
    "Shared",
    8,
    5,
    "Male",
    ["WiFi", "Kitchen", "Electricity Backup"],
  ],

  [
    21,
    8,
    "Single Room in Saddar Peshawar",
    "Private furnished room in a shared residence near Peshawar's main bazaar. Attached washroom, Wi-Fi, UPS, and access to a kitchen. Very affordable and conveniently located.",
    "Peshawar",
    "Saddar",
    "Saddar Road, Peshawar",
    34.0017,
    71.565,
    12000,
    "Room",
    1,
    1,
    "Male",
    ["WiFi", "Furnished", "Electricity Backup", "Kitchen"],
  ],

  [
    24,
    8,
    "Apartment near Saddar Peshawar",
    "Decent 1-bedroom apartment close to Saddar's commercial hub. Includes a kitchen, tiled bathroom, and a balcony. UPS backup for 6 hours, a gas connection, and a water tank on the roof.",
    "Peshawar",
    "Saddar",
    "Near Cinema Road, Saddar, Peshawar",
    34.0004,
    71.5635,
    32000,
    "Apartment",
    1,
    1,
    "Any",
    ["Electricity Backup", "Balcony", "Kitchen"],
  ],

  // ─── Gulbahar ─────────────────────────────────────────────────────────────
  [
    27,
    8,
    "Upper Portion in Gulbahar Peshawar",
    "Nice upper portion with 2 bedrooms, a lounge, and a rooftop space. Gas, electricity, and a water boring are all functional. The area has a local market, pharmacy, and a mosque within walking distance.",
    "Peshawar",
    "Gulbahar",
    "Gulbahar Colony, Peshawar",
    34.0255,
    71.5538,
    45000,
    "Private",
    2,
    1,
    "Any",
    ["Electricity Backup", "Balcony", "Kitchen"],
  ],

  [
    0,
    8,
    "Lower Portion in Gulbahar Peshawar",
    "Clean lower portion of a house in a quiet Gulbahar street. 2 bedrooms, attached baths, a compact kitchen, and a private lawn area. Separate entrance with a lockable gate. Good water supply.",
    "Peshawar",
    "Gulbahar",
    "Street 4, Gulbahar No. 2, Peshawar",
    34.026,
    71.5545,
    42000,
    "Private",
    2,
    2,
    "Any",
    ["Electricity Backup", "Parking", "Kitchen"],
  ],

  [
    3,
    8,
    "1-Bed Apartment in Gulbahar Peshawar",
    "Affordable 1-bedroom apartment near Gulbahar bus stop. Fitted kitchen, tiled bathroom, and a split AC. Backup generator in the building. Close to Ring Road for quick city access.",
    "Peshawar",
    "Gulbahar",
    "Gulbahar No. 1, Peshawar",
    34.0249,
    71.553,
    30000,
    "Apartment",
    1,
    1,
    "Any",
    ["AC", "Electricity Backup", "Kitchen"],
  ],
];

// ─── Build full property document from spec ────────────────────────────────
function buildProperty(spec, idx, ownerIds) {
  const [
    imgOffset,
    ownerIdx,
    title,
    description,
    city,
    area,
    address,
    lat,
    lng,
    price,
    propertyType,
    totalRooms,
    availableRooms,
    genderType,
    facilities,
  ] = spec;

  const s = getStatus(idx);
  const imgCount = 3 + (idx % 2 === 0 ? 1 : 0); // 3 or 4 images alternating

  return {
    owner: ownerIds[ownerIdx % ownerIds.length],
    title,
    description,
    city,
    area,
    address,
    latitude: parseFloat(lat.toFixed(6)),
    longitude: parseFloat(lng.toFixed(6)),
    location: {
      type: "Point",
      coordinates: [parseFloat(lng.toFixed(6)), parseFloat(lat.toFixed(6))],
    },
    price,
    propertyType,
    totalRooms,
    availableRooms,
    genderType,
    facilities,
    images: imgs(imgOffset, imgCount),
    isAvailable: s === "APPROVED",
    views:
      s === "APPROVED"
        ? Math.floor((idx * 137 + 23) % 490) + 10
        : Math.floor((idx * 17) % 20),
    status: s,
    isDeleted: false,
  };
}

// ─── Main seeder ──────────────────────────────────────────────────────────────
async function seed() {
  await connectDB();

  // ── Clear mode ───────────────────────────────────────────────────────────
  if (CLEAR) {
    console.log("\n🗑  SEED_CLEAR=true — removing seeded data...");
    const seededLandlords = await Landlord.find({
      email: { $regex: SEED_TAG + "$" },
    }).select("_id");
    const ids = seededLandlords.map((l) => l._id);

    if (ids.length > 0) {
      // Bypass the soft-delete pre-find middleware by using deleteMany directly on the collection
      const propResult = await Property.collection.deleteMany({
        owner: { $in: ids },
      });
      const landlordResult = await Landlord.deleteMany({ _id: { $in: ids } });
      console.log(`   ✅ Deleted ${propResult.deletedCount} properties`);
      console.log(`   ✅ Deleted ${landlordResult.deletedCount} landlords`);
    } else {
      console.log("   ℹ  No seeded records found to clear.");
    }

    if (process.env.SEED_CLEAR_ONLY === "true") {
      await mongoose.disconnect();
      process.exit(0);
    }
  }

  // ── Insert Landlords ─────────────────────────────────────────────────────
  console.log("\n👤 Creating landlords...");

  // Check and skip already-existing seeded emails
  const existingEmails = new Set(
    (
      await Landlord.find({ email: { $regex: SEED_TAG + "$" } }).select("email")
    ).map((l) => l.email),
  );

  const newLandlordDocs = LANDLORD_DATA.filter(
    (l) => !existingEmails.has(l.email),
  ).map((l) => ({
    name: l.name,
    email: l.email,
    password: "Seed@1234",
    phone: l.phone,
    cnic: l.cnic,
    businessAddress: l.businessAddress,
    role: "landlord",
    isVerified: true,
    isActive: true,
    profileImage: { public_id: null, secure_url: null },
  }));

  let insertedLandlords = [];

  if (newLandlordDocs.length > 0) {
    // Use Mongoose model to trigger pre-save password hashing
    insertedLandlords = await Landlord.insertMany(newLandlordDocs);
    console.log(`   ✅ Inserted ${insertedLandlords.length} new landlords`);
  } else {
    console.log("   ℹ  All landlords already exist — skipping.");
  }

  // Fetch all seeded landlord IDs (existing + newly inserted)
  const allSeededLandlords = await Landlord.find({
    email: { $regex: SEED_TAG + "$" },
  }).select("_id");
  const ownerIds = allSeededLandlords.map((l) => l._id);

  if (ownerIds.length === 0) {
    console.error("❌ No seeded landlords found. Aborting property insertion.");
    await mongoose.disconnect();
    process.exit(1);
  }

  // ── Insert Properties ────────────────────────────────────────────────────
  console.log("\n🏠 Inserting properties...");

  const propertyDocs = SPECS.map((spec, idx) =>
    buildProperty(spec, idx, ownerIds),
  );

  await Property.collection.insertMany(propertyDocs);

  const total = propertyDocs.length;
  const approved = propertyDocs.filter((p) => p.status === "APPROVED").length;
  const pending = propertyDocs.filter((p) => p.status === "PENDING").length;
  const rejected = propertyDocs.filter((p) => p.status === "REJECTED").length;

  console.log(`   ✅ Inserted ${total} properties`);
  console.log(
    `      APPROVED: ${approved} | PENDING: ${pending} | REJECTED: ${rejected}`,
  );

  // ── Sample output ────────────────────────────────────────────────────────
  const sample = propertyDocs.find((p) => p.status === "APPROVED");
  console.log("\n📦 Sample property:");
  console.log(
    JSON.stringify(
      {
        title: sample.title,
        city: sample.city,
        area: sample.area,
        price: sample.price,
        propertyType: sample.propertyType,
        status: sample.status,
        latitude: sample.latitude,
        longitude: sample.longitude,
        facilities: sample.facilities,
        images: sample.images.length + " images",
      },
      null,
      2,
    ),
  );

  // ── Cities summary ───────────────────────────────────────────────────────
  const citySummary = {};
  propertyDocs.forEach((p) => {
    citySummary[p.city] = (citySummary[p.city] || 0) + 1;
  });
  console.log("\n📍 By city:", citySummary);

  console.log("\n✅ Seeding complete!\n");
  await mongoose.disconnect();
  process.exit(0);
}

seed().catch((err) => {
  console.error("❌ Seeder error:", err.message);
  process.exit(1);
});
